version: '2.1'
services:
  web:
    build: .
    command: npm run start-dev
    environment:
      - DB=test
      - DB_USER=test
      - DB_PASS=test
      - DB_HOST=db 
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mdillon/postgis:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
